export default{
    PlaylistIcon:require('../assets/images/PlaylistIcon.png'),
    checkboxTickBlue:require('../assets/images/checkboxTickBlue.png'),
    downloadIconWhite:require('../assets/images/downloadIconWhite.png'),
    guardianOfGalaxyMovie:require('../assets/images/guardianOfGalaxyMovie.jpg'),
    settingIcon:require('../assets/images/settingIcon.png'),
    BellIcon:require('../assets/images/BellIcon.png'),
    GuardianOfTheGalaxyTitile:require('../assets/images/GuardianOfTheGalaxyTitile.png'),
    sandManTitle:require('../assets/images/sandManTitle.png'),
    sandManShow:require('../assets/images/sandManShow.jpg'),
    playIconWhite:require('../assets/images/playIconWhite.png'),
    showsIcon:require('../assets/images/showsIcon.png'),
    showIconActive:require('../assets/images/showIconActive.png'),
    radioIcon:require('../assets/images/radioIcon.png'),
    radioIconActive:require('../assets/images/radioIconActive.png'),
    movieIcon:require('../assets/images/movieIcon.png'),
    movieIconActive:require('../assets/images/movieIconActive.png'),
    appIconSiderBar:require('../assets/images/appIconSiderBar.png'),
    favlistIcon:require('../assets/images/favlistIcon.png'),
    favlistIconActive:require('../assets/images/favlistIconActive.png'),
    TvIcon:require('../assets/images/TvIcon.png'),
    TvIconActive:require('../assets/images/TvIconActive.png'),
    searchIcon:require('../assets/images/searchIcon.png'),
    searchIconActive:require('../assets/images/searchIconActive.png'),
    MicIcon:require('../assets/images/MicIcon.png'),
    microphone:require('../assets/images/microphone.png'),
    PremiumIcon:require('../assets/images/PremiumIcon.png'),
    LockIcon:require('../assets/images/LockIcon.png'),
    homeIcon:require('../assets/images/homeIcon.png'),
    homeIconActive:require('../assets/images/homeIconActive.png'),
    VideoPlaceHolder:require('../assets/images/VideoPlaceHolder.png'),
    playbuttonarrowhead:require('../assets/images/playbuttonarrowhead.png'),
    maximizeIcon:require('../assets/images/maximize.png'),
    movieTrailerIcon:require('../assets/images/movieTrailer.png'),
    wishlistIcon:require('../assets/images/wishlist.png'),
    pauseIcon:require('../assets/images/pause.png'),
    skip10SecIcon:require('../assets/images/skip10Sec.png'),
    prev10SecIcon:require('../assets/images/prev10Sec.png'),
    LoginBg:require('../assets/images/LoginBg.png'),
    SubscitionIcon:require('../assets/images/SubscitionIcon.gif'),
    SubscitionIcon1:require('../assets/images/SubscitionIcon.png'),

    //sample data
    popularMovie1:require('../assets/images/popularMovie1.jpg'),
    popularMovie2:require('../assets/images/popularMovie2.jpg'),
    popularMovie3:require('../assets/images/popularMovie3.jpg'),
    popularMovie4:require('../assets/images/popularMovie4.jpg'),
    popularMovie5:require('../assets/images/popularMovie5.jpg'),

    popularShow1:require('../assets/images/popularShow1.jpg'),
    popularShow2:require('../assets/images/popularShow2.jpg'),
    popularShow3:require('../assets/images/popularShow3.jpg'),
    popularShow4:require('../assets/images/popularShow4.jpg'),
    popularShow5:require('../assets/images/popularShow5.jpg'),

    continueWatching1:require('../assets/images/continueWatching1.png'),
    continueWatching2:require('../assets/images/continueWatching2.png'),
    continueWatching3:require('../assets/images/continueWatching3.png'),
    continueWatching4:require('../assets/images/continueWatching4.png'),
    continueWatching5:require('../assets/images/continueWatching5.png'),

    actionCat1:require('../assets/images/actionCat1.jpg'),
    actionCat2:require('../assets/images/actionCat2.jpg'),
    actionCat3:require('../assets/images/actionCat3.jpg'),
    actionCat4:require('../assets/images/actionCat4.jpg'),
    actionCat5:require('../assets/images/actionCat5.jpg'),

    comedyCat1:require('../assets/images/comedyCat1.jpg'),
    comedyCat2:require('../assets/images/comedyCat2.jpg'),
    comedyCat3:require('../assets/images/comedyCat3.jpg'),
    comedyCat4:require('../assets/images/comedyCat4.jpg'),
    comedyCat5:require('../assets/images/comedyCat5.jpg'),

    dramaCat1:require('../assets/images/dramaCat1.jpg'),
    dramaCat2:require('../assets/images/dramaCat2.jpg'),
    dramaCat3:require('../assets/images/dramaCat3.jpg'),
    dramaCat4:require('../assets/images/dramaCat4.jpg'),
    dramaCat5:require('../assets/images/dramaCat5.jpg'),

    showDrama1:require('../assets/images/showDrama1.png'),
    showDrama2:require('../assets/images/showDrama2.png'),
    showDrama3:require('../assets/images/showDrama3.jpg'),
    showDrama4:require('../assets/images/showDrama4.png'),
    showDrama5:require('../assets/images/showDrama5.png'),
    showDrama6:require('../assets/images/showDrama6.png'),
    showDrama7:require('../assets/images/showDrama7.jpg'),

    TvDemoImage:require('../assets/images/TvDemoImage.jpg'),
    

}