export default{
    PlaylistIcon:require('../assets/images/PlaylistIcon.png'),
    checkboxTickBlue:require('../assets/images/checkboxTickBlue.png'),
    downloadIconWhite:require('../assets/images/downloadIconWhite.png'),
    settingIcon:require('../assets/images/settingIcon.png'),
    BellIcon:require('../assets/images/BellIcon.png'),
    playIconWhite:require('../assets/images/playIconWhite.png'),
    showsIcon:require('../assets/images/showsIcon.png'),
    showIconActive:require('../assets/images/showIconActive.png'),
    radioIcon:require('../assets/images/radioIcon.png'),
    radioIconActive:require('../assets/images/radioIconActive.png'),
    movieIcon:require('../assets/images/movieIcon.png'),
    movieIconActive:require('../assets/images/movieIconActive.png'),
    appIconSiderBar:require('../assets/images/appIconSiderBar.png'),
    favlistIcon:require('../assets/images/favlistIcon.png'),
    favlistIconActive:require('../assets/images/favlistIconActive.png'),
    TvIcon:require('../assets/images/TvIcon.png'),
    TvIconActive:require('../assets/images/TvIconActive.png'),
    searchIcon:require('../assets/images/searchIcon.png'),
    searchIconActive:require('../assets/images/searchIconActive.png'),
    MicIcon:require('../assets/images/MicIcon.png'),
    microphone:require('../assets/images/microphone.png'),
    PremiumIcon:require('../assets/images/PremiumIcon.png'),
    LockIcon:require('../assets/images/LockIcon.png'),
    homeIcon:require('../assets/images/homeIcon.png'),
    homeIconActive:require('../assets/images/homeIconActive.png'),
    VideoPlaceHolder:require('../assets/images/VideoPlaceHolder.png'),
    playbuttonarrowhead:require('../assets/images/playbuttonarrowhead.png'),
    maximizeIcon:require('../assets/images/maximize.png'),
    movieTrailerIcon:require('../assets/images/movieTrailer.png'),
    wishlistIcon:require('../assets/images/wishlist.png'),
    pauseIcon:require('../assets/images/pause.png'),
    skip10SecIcon:require('../assets/images/skip10SecIcon.png'),
    prev10SecIcon:require('../assets/images/prev10SecIcon.png'),
    LoginBg:require('../assets/images/LoginBg.png'),
    SubscitionIcon1:require('../assets/images/SubscitionIcon.png'),
    muteIcon:require('../assets/images/mute.png'),
    unmuteIcon:require('../assets/images/unmute.png'),
    fast_forward:require('../assets/images/fast_forward.png'),
    rewind_button:require('../assets/images/rewind_button.png'),
    next:require('../assets/images/next.png'),
    previous:require('../assets/images/previous.png'),
    reload:require('../assets/images/reload.png'),
    Defaultuser:require('../assets/images/Defaultuser.png'),
    check:require('../assets/images/check.png'),
    remove:require('../assets/images/remove.png'),

    //sample data

    continueWatching1:require('../assets/images/continueWatching1.png'),
    continueWatching2:require('../assets/images/continueWatching2.png'),
    continueWatching3:require('../assets/images/continueWatching3.png'),
    continueWatching4:require('../assets/images/continueWatching4.png'),
    continueWatching5:require('../assets/images/continueWatching5.png'),

    TvDemoImage:require('../assets/images/TvDemoImage.jpg'),
    

}